version: '2.1'
services:
  events-db:
    container_name: events-db
    build: ./project/db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  events-service:
    container_name: events-service
    build: ./
    expose:
      - '5000'
    environment:
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@events-db:5432/events_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@events-db:5432/events_test
    depends_on:
      events-db:
        condition: service_healthy
    links:
      - events-db
    command: gunicorn -b 0.0.0.0:5000 manage:app

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      events-service:
        condition: service_started
    links:
      - events-service
